title: Demeo Modding Wiki
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark" 

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/JoeZwet/DemeoModdingWiki"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Upper right nav links
aux_links:
  "Demeo Modding Group on Discord":
    - "//discord.gg/XYphVbfaqh"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

collections:
  # Define a collection named "guides", its documents reside in the "_guides" directory
  guides:
    output: true
  references:
    output: true

just_the_docs:
  collections:
    guides:
      name: Guides
    references:
      name: References